### ISSUE TITLE
Inquiry About Support for ApprovalSignature in CertType

### ISSUE THREAD

**Issue by nguyentanluctego** [digitorus/pdfsign#51]
I noticed that the current implementation of the CertType seems to focus on CertificationSignature. I wanted to ask if there is any support or planned support for using ApprovalSignature as a CertType. This functionality would be beneficial for scenarios where document approval is required rather than certification.

I tried signing the file [demo.pdf](https://github.com/user-attachments/files/17629051/pdffomsign.pdf) with CertificationSignature, but Adobe cannot detect the digital signature. However, when I sign using your PDF file in testfiles, Adobe can detect the digital signature. Can you let me know why my file cannot be signed digitally?

**Comment by vanbroup** [comment]
@nguyentanluctego, it looks like your demo file is corrupt because `startxref` can't be 0:

```pdf
endobj
startxref
 0
%%EOF
```

Your reader might be able to fix this, but once the PDF is signed, any modifications will invalidate the signature.

I've just added support for `ApprovalSignature` and `TimeStampSignature`, along with other improvements to enhance compatibility.
